### ISSUE TITLE
ValueError: time data 'Tuesday, 21 November 2017 at 08:05 UTC+05:30' does not match format '%A, %B %d, %Y at %H:%M%p' (search)

### ISSUE THREAD

**Issue by SpideySanthosh** [MasterScrat/Chatistics#17]
*While parsing messenger data , i got this*

Unexpected date format. Falling back to infer_datetime_format, parsing will be slower.
Traceback (most recent call last):
  File "C:\Users\San\Anaconda3\lib\site-packages\pandas\core\tools\datetimes.py", line 444, in _convert_listlike
    values, tz = tslib.datetime_to_datetime64(arg)
  File "pandas/_libs/tslib.pyx", line 1810, in pandas._libs.tslib.datetime_to_datetime64 (pandas\_libs\tslib.c:33275)
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parsers/messenger.py", line 87, in <module>
    timestamp = time.mktime(pd.to_datetime(content, format='%A, %B %d, %Y at %H:%M%p', exact=False).timetuple())
  File "C:\Users\San\Anaconda3\lib\site-packages\pandas\core\tools\datetimes.py", line 518, in to_datetime
    result = _convert_listlike(np.array([arg]), box, format)[0]
  File "C:\Users\San\Anaconda3\lib\site-packages\pandas\core\tools\datetimes.py", line 447, in _convert_listlike
    raise e
  File "C:\Users\San\Anaconda3\lib\site-packages\pandas\core\tools\datetimes.py", line 414, in _convert_listlike
    errors=errors)
  File "pandas/_libs/tslib.pyx", line 3701, in pandas._libs.tslib.array_strptime (pandas\_libs\tslib.c:63962)
ValueError: time data 'Tuesday, 21 November 2017 at 08:05 UTC+05:30' does not match format '%A, %B %d, %Y at %H:%M%p' (search)

**Comment by SpideySanthosh** [comment]
`timestamp = time.mktime(pd.to_datetime(content, format='%A, %d %B %Y at %H:%M', exact=False).timetuple())`

solved the issue

**Comment by MasterScrat** [comment]
Ah yes I see the problem, when it falls back to `infer_datetime_format` it still tries to parse the date with the wrong format.

Please don't close the issue before the fix is pushed to master!
