### ISSUE TITLE
charmap decode error - hangouts

### ISSUE THREAD

**Issue by SpideySanthosh** [MasterScrat/Chatistics#18]
while parsing hangouts json file

Traceback (most recent call last):
  File "parsers/hangouts.py", line 24, in <module>
    archive = json.load(open(filePath))
  File "C:\Users\San\Anaconda3\lib\json\__init__.py", line 296, in load
    return loads(fp.read(),
  File "C:\Users\San\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 103737: character maps to <undefined>

**Comment by MasterScrat** [comment]
Ah yes, this is the same issue as we had with Messenger in #4.

Please don't close the issue before the fix is pushed to master!
