### ISSUE TITLE
Value Error in analyse.py with telegram.pkl

### ISSUE THREAD

**Issue by yeswecoin** [MasterScrat/Chatistics#25]
Hi there, thanks for these scripts. 

when adding telegram data I get following error:

` python analyse.py --data data/*`

```
Traceback (most recent call last):
  File "Chatistics/lib/python3.6/site-packages/matplotlib/colors.py", line 132, in to_rgba
    rgba = _colors_full_map.cache[c, alpha]
KeyError: (736755, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "analyse.py", line 97, in <module>
    main()
  File "analyse.py", line 93, in main
    render(data, bin_width=args.bin_width, plot_density=args.density)
  File "analyse.py", line 81, in render
    print(plot)
  File "Chatistics/lib/python3.6/site-packages/ggplot/ggplot.py", line 116, in __repr__
    self.make()
  File "Chatistics/lib/python3.6/site-packages/ggplot/ggplot.py", line 636, in make
    layer.plot(ax, facetgroup, self._aes, **kwargs)
  File "Chatistics/lib/python3.6/site-packages/ggplot/geoms/geom_histogram.py", line 51, in plot
    ax.hist(x, **params)
  File "Chatistics/lib/python3.6/site-packages/matplotlib/__init__.py", line 1717, in inner
    return func(ax, *args, **kwargs)
  File "Chatistics/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 6137, in hist
    color = mcolors.to_rgba_array(color)
  File "/Chatistics/lib/python3.6/site-packages/matplotlib/colors.py", line 233, in to_rgba_array
    result[i] = to_rgba(cc, alpha)
  File "Chatistics/lib/python3.6/site-packages/matplotlib/colors.py", line 134, in to_rgba
    rgba = _to_rgba_no_colorcycle(c, alpha)
  File "Chatistics/lib/python3.6/site-packages/matplotlib/colors.py", line 185, in _to_rgba_no_colorcycle
    raise ValueError("Invalid RGBA argument: {!r}".format(orig_c))
ValueError: Invalid RGBA argument: 736755
```

using `python analyse.py --plot-density --data data/*` I get following:

```
Traceback (most recent call last):
  File "analyse.py", line 97, in <module>
    main()
  File "analyse.py", line 93, in main
    render(data, bin_width=args.bin_width, plot_density=args.density)
  File "analyse.py", line 81, in render
    print(plot)
  File "Chatistics/lib/python3.6/site-packages/ggplot/ggplot.py", line 116, in __repr__
    self.make()
  File "Chatistics/lib/python3.6/site-packages/ggplot/ggplot.py", line 641, in make
    self.apply_axis_labels()
  File "Chatistics/lib/python3.6/site-packages/ggplot/ggplot.py", line 231, in apply_axis_labels
    labels.append(self.xtick_formatter(label_text))
  File "Chatistics/lib/python3.6/site-packages/matplotlib/dates.py", line 578, in __call__
    dt = num2date(x, self.tz)
  File "Chatistics/lib/python3.6/site-packages/matplotlib/dates.py", line 466, in num2date
    return _from_ordinalf(x, tz)
  File "Chatistics/lib/python3.6/site-packages/matplotlib/dates.py", line 279, in _from_ordinalf
    dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)
ValueError: year 3997345 is out of range
```

Everything works normal using only facebook messages.
Any idea how to fix that?

**Comment by mhraza95** [comment]
Anyone solved this issue??

**Comment by MasterScrat** [comment]
Fixed in new version!
